database:
    driverClass: org.h2.Driver
    user: sa
    password: 
    url: jdbc:h2:grouptabs
    
server:
    applicationConnectors:
        - type: http
          port: 8080
    adminConnectors:
        - type: http
          port: 8282
